name: Publish to Modrinth

on:
  push:
    tags: [created]

jobs:
  modrinth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
      - uses: ./gradlew build
      - uses: Kir-Antipov/mc-publish@v3.1
        with:
          modrinth-id: E4fbH01j
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
